language: ruby
sudo: false
before_script:
  - bundle update
cache: bundler
rvm:
  - 2.0.0-p648
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby-9.0.5.0
  - jruby-head
  - rbx-2
  - rbx-3
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
